### ISSUE TITLE
set.seed for position?

### ISSUE THREAD

**Issue by zx8754** [jolars/shiny-server#1]
How can we ensure the circles are positioned exactly the same place for the same input every time.

For example, using this app, I plotted 2 sets `A=5`, `B=3`, `A&B=2`. But every time when I increase `A` value by one, `A=6`, then decrease back to `A=5`. The plot positions are not the same as before.

![screen shot 06-08-17 at 07 58 pm](https://user-images.githubusercontent.com/5212915/26945945-6ddee7b6-4c85-11e7-95f9-413b6538a18b.PNG)

**Comment by jolars** [comment]
This is by design. I so far haven't included any way of modifying the layout after the plot has been computed so I want users to be able to re-roll the layout. However, I think that a separate argument with `set.seed` might be useful here so I might add that as an option.
