### ISSUE TITLE
App not available

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [jolars/shiny-server#2]
Hi,

I wanted to try your app under the given [link](http://jolars.co/eulerr) but it was not available.

Best regards,
Alex

**Comment by jolars** [comment]
Hello,

Try http://eulerr.co/

Where did you find the link jolars.co/eulerr? It's outdated.

Cheers,
Johan

**Comment by jolars** [comment]
Oh, now I see. We're in this old repository. 

The code for eulerr.co is in https://github.com/jolars/eulerr.co

**Comment by AlexanderBartholomaeus** [comment]
Thank you for the fast answer!
